#!/bin/sh
#
# An example hook script for the "post-receive" event.
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for a sample, or uncomment the next line and
# rename the file to "post-receive".

#. /usr/share/doc/git-core/contrib/hooks/post-receive-email

deploy() {
    local refname="$1"
    local destination="$2"
    local destsuffix="$3"
    local branch=$(echo "$refname" | cut -d '/' -f 3)
    echo "deploing branch $branch"
    if [ "$branch" ] ; then

        local branch_path="$branch"
        #[ "$branch" = "master" ] && branch_path="prod"

        local destdir="$destination/$branch_path/$destsuffix"
        rm -rf "$destdir"
        mkdir -p -m 770 "$destdir"
        git archive --format=tar $branch | (cd "$destdir" && tar xf -)
        cd "$destdir"
        find . -type d -exec chmod 770 {} \;
        find . -type f -exec chmod 660 {} \;
    fi
}

while read oldrev newrev refname ; do
    deploy "$refname" "/home/webuser/www" "www"
done
