#!/bin/sh

detect_editor() {
	for i in gthumb gimp gpicview ristretto eog okular ; do
		which "$i" && break
	done
}

msg() {
	which notify-send > /dev/null && notify-send "$1" 2> /dev/null
}

win=
xdir=$(pwd)
xeditor=1
upload=1

until [ -z "$1" ] ; do
	case "$1" in
		--window)
			win="-u"
		;;
	    --no-editor)
			xeditor=
		;;
		--no-upload)
			upload=
		;;
		*)
			echo "Usage $0 --window --no-editor --no-upload --help"
			exit 1
		;;
	esac
	shift
done


if [ -n "$xeditor" ] ; then
	xeditor=$(detect_editor)
	[ -n "$xeditor" ] && xeditor="-e \"$xeditor \\\$f\""
fi

tmp=$(mktemp -dt scrot.XXXXXXXXXX)
cd "$tmp"

eval "scrot $win $xeditor"

cd "$xdir"
[ -n "$xeditor" ] && rm "$tmp"/*_scrot.png

retval=0
if [ -n "$upload" ] ; then
	for i in $tmp/* ; do
		if [ -e "$i" ] ; then
			url=$(imgbinit "$i")
			if [ -n "$url"] ; then
				break
			fi
		fi
	done
fi

[ $retval = 0 ] && rm -rf "$tmp"

exit $retval
